#include "horelac/services/ScheduleService.hpp"
#include <catch2/catch_test_macros.hpp>
#include <map>
using namespace horelac;
namespace {
class MemoryRepo final:public persistence::IScheduleRepository{public:domain::Calendar calendar;std::vector<domain::Participant> participants;std::vector<domain::AvailabilityInterval> intervals;void migrate()override{}domain::CalendarId create_calendar(const domain::Calendar& c)override{calendar=c;calendar.id=1;return 1;}std::optional<domain::Calendar> find_calendar(domain::CalendarId id)override{return id==calendar.id?std::optional{calendar}:std::nullopt;}std::vector<domain::Calendar> list_open_calendars(domain::Snowflake,domain::Snowflake)override{return {calendar};}void update_calendar_state(domain::CalendarId,domain::CalendarState s)override{calendar.state=s;}void delete_calendar(domain::CalendarId)override{calendar={};}domain::Participant upsert_participant(const domain::Participant& p)override{auto x=p;x.id=static_cast<long long>(participants.size()+1);participants.push_back(x);return x;}std::optional<domain::Participant> find_participant(domain::CalendarId,domain::Snowflake)override{return std::nullopt;}int participant_count(domain::CalendarId)override{return static_cast<int>(participants.size());}std::vector<domain::Participant> list_participants(domain::CalendarId)override{return participants;}domain::IntervalId add_interval(const domain::AvailabilityInterval& i)override{auto x=i;x.id=static_cast<long long>(intervals.size()+1);intervals.push_back(x);return x.id;}std::vector<domain::AvailabilityInterval> list_intervals(domain::CalendarId,domain::LocalDate first,domain::LocalDate last)override{std::vector<domain::AvailabilityInterval> out;for(auto x:intervals)if(x.date>=first&&x.date<=last)out.push_back(x);return out;}void remove_interval(domain::IntervalId,domain::ParticipantId)override{}void clear_participant(domain::CalendarId,domain::Snowflake)override{participants.clear();intervals.clear();}void set_calendar_message(domain::CalendarId,domain::Snowflake,domain::Snowflake,domain::Snowflake,int,bool)override{}domain::EventId create_event(const domain::Event&)override{return 1;}void set_attendance(const domain::AttendanceRecord&)override{}};
}
TEST_CASE("service rejects dates outside month") {MemoryRepo repo;services::ScheduleService service(repo);domain::CalendarConfig cfg;cfg.month=std::chrono::year{2026}/8;auto calendar=service.create_calendar({1,2,3,"Test","","en",cfg});REQUIRE_THROWS(service.add_availability({calendar.id,4,domain::IdentityMode::anonymous,std::nullopt,std::nullopt,{std::chrono::year{2026}/9/1},1080,1200}));}
TEST_CASE("anonymous participants are never listed") {MemoryRepo repo;services::ScheduleService service(repo);domain::CalendarConfig cfg;cfg.month=std::chrono::year{2026}/8;auto calendar=service.create_calendar({1,2,3,"Test","","en",cfg});service.add_availability({calendar.id,4,domain::IdentityMode::anonymous,std::nullopt,std::nullopt,{std::chrono::year{2026}/8/5},1080,1200});REQUIRE(service.public_participants(calendar.id).empty());}

